[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"

# Health check configuration - REMOVE PORT, Railway sets it automatically
[healthcheck]
path = "/health"
timeout = 30